### ISSUE TITLE
when do you plan to release the code?

### ISSUE THREAD

**Issue by Guptajakala** [PruneTruong/GOCor#1]
Hi, I'm interested in applying this method in my research, do you have an estimate of when to release to code?

**Comment by PruneTruong** [comment]
Hi, we are hoping to release the code in 1 or 2 months !

**Comment by phiphiphi31** [comment]
eager to see your  code

**Comment by PruneTruong** [comment]
Hi, unfortunately we are still in the process of getting the authorization to release the code. Hopefully, we can release it in January. Sorry for the delay !

**Comment by gtinchev** [comment]
Hi, is there any update on this?

**Comment by PruneTruong** [comment]
Hi, I (finally) obtained authorization to release the inference code ! it's online. Will release evaluation code and general training pipeline in a general repo at https://github.com/PruneTruong/PDCNet. 
Sorry for the delay and let me know if there is any issues.
